
//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by Tools.ExcelParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepEngine                                          
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using Lockstep.Serialization;
using Lockstep.Math;

namespace Lockstep.Game{
    public partial class Table_ConfigBullet : TableData<Table_ConfigBullet>
    {
        const string tableName = "ConfigBullet";
        public override string Name() { return tableName; }               
        
        /// id
        public UInt16 asset;        
        /// 
        public Boolean bullet_canDestoryIron;        
        /// 
        public Boolean bullet_canDestoryGrass;        
        /// 
        public String unit_name;        
        /// 
        public Int32 unit_health;        
        /// 
        public Int32 unit_damage;        
        /// 
        public LFloat move_moveSpd;        
        /// 
        public LFloat move_maxMoveSpd;

        protected override void DoParseData(Deserializer reader){ 
            asset = reader.ReadUInt16(); 
            bullet_canDestoryIron = reader.ReadBoolean(); 
            bullet_canDestoryGrass = reader.ReadBoolean(); 
            unit_name = reader.ReadString(); 
            unit_health = reader.ReadInt32(); 
            unit_damage = reader.ReadInt32(); 
            move_moveSpd = reader.ReadLFloat(); 
            move_maxMoveSpd = reader.ReadLFloat();
        }
    }
}